# Generated by Django 4.2.3 on 2023-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personalinformation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(upload_to='api/static/api/photo/'),
        ),
    ]
