# Generated by Django 4.2.3 on 2023-09-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personalinformation_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='educations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.educations'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skills'),
        ),
    ]
