# Generated by Django 4.2.3 on 2023-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_educations_user_remove_skills_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='skills',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='educations',
            field=models.ManyToManyField(to='api.educations'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='skills',
            field=models.ManyToManyField(to='api.skills'),
        ),
    ]
